# Generated by Django 5.2.6 on 2025-10-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ruta_imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
