# Generated by Django 5.2.6 on 2025-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0002_remove_producto_ruta_imagen_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
