# Generated by Django 5.2.6 on 2025-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0003_alter_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=20),
        ),
    ]
