# Generated by Django 5.2.6 on 2025-11-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0004_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=15),
        ),
    ]
