# Generated by Django 5.2.6 on 2025-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0005_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista Financiero')], max_length=20),
        ),
    ]
