# Generated by Django 5.2.6 on 2025-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalooo', '0006_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista Financiero')], default='analista', max_length=20),
        ),
    ]
